language: ruby
before_install:
#  - gem uninstall bundler --all --executables
#  - gem install bundler --version '~> 1.7.0'
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq -y bsdtar
#  - rvm @global do gem uninstall bundler --all --executables
#  - gem uninstall bundler --all --executables
#  - gem install bundler --version '~> 1.7.0'
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - bundle exec rake
  - bundle exec rake build
